[toolchain]
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ratings = "63uX58srXmpgXzZpdZUpBjDGWJj2fje227ecoVLS1Jvx"

[programs.localnet]
ratings = "BjGzpwcLwZn29m8GVykTPVR6WsGQEf1vYhAF7gKnQzJX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "bosq5LCREmQ4aiSwzYdvD7N1thoASZzHVqvCA1D2Cg5.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
